version: "3.7"

services:
  phpfpm:
    volumes: &appvolumes-linux
      - .:/var/www/html

  phpfpm_xdebug:
    volumes: *appvolumes-linux

  nginx:
    volumes: *appvolumes-linux

  node:
    volumes: *appvolumes-linux
